### ISSUE TITLE
[Proposal] Track workout activity

### ISSUE THREAD

**Issue by fattal28** [p-karanthaker/puregym-tracker#1]
I'm aware that the PureGym website (and app) give logged in users the ability to track their personal workout activity. This data includes the date and time of a visit, the duration and which gym it was at. 

It would be really awesome if this data could be scraped into a CSV file, in a similar manner to how the gym's activity is being scraped at the moment.

**Comment by p-karanthaker** [comment]
Hi, thanks for the interest. I'm actually no longer a member at PureGym so wouldn't be able to test it myself. If you can provide some info about the process I'd be happy to try and implement it.

I think at the very least I'd need:
- the webpage address
- a copy of the html on that page
- maybe some screenshots of the page too

**Comment by fattal28** [comment]
Thanks for picking this up!
That would be awesome. I would love to lend a hand, although I must warn you I've never built anything in PowerShell/Shell!

**Webpage URL**: https://www.puregym.com/members/activity/

**Copy of HTML** (in a Gist): https://gist.github.com/fattal28/b2a5955cd07b26933a775b429781a416

Screenshots attached.
(Note that I've masked the full gym name for privacy.)

<img width="1680" alt="Screenshot 2020-02-24 at 22 55 54" src="https://user-images.githubusercontent.com/32335308/75198613-fb1de380-5758-11ea-9d76-f3d3e62b6be4.png">
<img width="1680" alt="Screenshot 2020-02-24 at 22 58 53" src="https://user-images.githubusercontent.com/32335308/75198769-4d5f0480-5759-11ea-87dd-7f2b53734d73.png">

**Comment by p-karanthaker** [comment]
Closing as this project is now stale and I am not a member of the gym any more so unable to test changes. Please check out https://github.com/2t6h/puregym-attendance since that appears to be more current.
