### ISSUE TITLE
Login flow changed

### ISSUE THREAD

**Issue by o-bean1** [p-karanthaker/puregym-tracker#2]
Hi - thanks for making this project! I've just got into computing and data analysis and love this project. I'm really interested in scraping this data and unfortunately the login no longer works - I think this is because the login process has been changed by puregym. Would you be able to try an update this project?

Thanks, Oli

**Comment by p-karanthaker** [comment]
Hi @o-bean1, I'm no longer a member at this gym so am unable to test any new login flows. I'd recommend following https://github.com/2t6h/puregym-attendance since that appears to be more current.
